version: '3'

services:
  ### Application server ########################
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
     - ./:/var/www
    # Storing logs
     - ./docker/nginx/logs:/var/log/nginx
    ports:
     - 8080:80
    links:
     - php-fpm

  ### PHP FastCGI Process Manager ###############
  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    volumes:
     - ./:/var/www
    environment:
     # Database
     - DB_CONNECTION=mysql
     - DB_HOST=mysql
     - DB_DATABASE=app
     - DB_USERNAME=app
     - DB_PASSWORD=app
     - DB_PORT=3306

     # Redis
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - BROADCAST_DRIVER=redis
     - CACHE_DRIVER=redis
     - SESSION_DRIVER=redis
     - QUEUE_DRIVER=redis

     # Mailer
     - MAIL_DRIVER=SMTP
     - MAIL_HOST=mailhog
     - MAIL_PORT=1025

     # Echo server
     - ECHO_SERVER_HOST=localhost
     - ECHO_SERVER_PORT=6002
    links:
     - mysql
     - redis
     - laravel-echo-server
     - mailhog

    ### PHP-CLI ##################################
    php-cli:
      build:
        context: docker/php-cli
        dockerfile: Dockerfile
      volumes:
      - ./:/var/www
      environment:
      # Database
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=app
      - DB_USERNAME=app
      - DB_PASSWORD=app
      - DB_PORT=3306

      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BROADCAST_DRIVER=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis

      # Mailer
      - MAIL_DRIVER=SMTP
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      links:
      - mysql
      - redis
      - laravel-echo-server
      - mailhog
      # Do not down CLI after run
      tty: true

  ### MySQL Database ##########################
  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    volumes:
     - ./docker/mysql/volume:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=secret
     - MYSQL_USER=app
     - MYSQL_PASSWORD=app
     - MYSQL_DATABASE=app
    ports:
     - 33061:3306

  ### Redis ##############################
  redis:
    build:
      context: docker/redis
      dockerfile: Dockerfile
    volumes:
      - redis:/data
    ports:
      - 63791:6379

  ### Node ###############################
  node:
    build:
      context: docker/node
      dockerfile: Dockerfile
    volumes:
    - ./:/var/www
    # Do not down CLI after run
    tty: true

  ### Laravel Echo Server ################
  laravel-echo-server:
    build:
      context: docker/laravel-echo-server
      dockerfile: Dockerfile
    volumes:
     - ./docker/laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json:ro
    ports:
     - 6002:6001
    links:
     - supervisor

  ### Supervisor ###################
  supervisor:
    build:
      context: docker/supervisor
      dockerfile: Dockerfile
    volumes:
     - ./:/var/www
    # Supervisor logs
     - ./docker/supervisor/logs:/home/logs
    # Supervisor configurations
     - ./docker/supervisor/conf.d:/etc/supervisor/conf.d
    environment:
    # Database
    - DB_CONNECTION=mysql
    - DB_HOST=mysql
    - DB_DATABASE=app
    - DB_USERNAME=app
    - DB_PASSWORD=app
    - DB_PORT=3306

    # Redis
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - BROADCAST_DRIVER=redis
    - CACHE_DRIVER=redis
    - SESSION_DRIVER=redis
    - QUEUE_DRIVER=redis

    # Mailer
    - MAIL_DRIVER=SMTP
    - MAIL_HOST=mailhog
    - MAIL_PORT=1025
    links:
     - mysql
     - redis
     - mailhog

  ### Mailhog (For mail testing) ####
  mailhog:
    build:
      context: docker/mailhog
      dockerfile: Dockerfile
    ports:
     # SMTP server
     - 1026:1025
     # Inbox web page
     - 8026:8025

volumes:
  redis:
    driver: local
  mysql:
    driver: local
